
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 25 20:32:26 EST 2009
//----------------------------------------------------

package com.pervasa.reactivity;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STOP = 9;
  public static final int PLUS = 18;
  public static final int RPAREN = 21;
  public static final int DEFINE = 4;
  public static final int LIST = 5;
  public static final int SEMI = 24;
  public static final int STAR = 19;
  public static final int IDENTIFIER = 3;
  public static final int EVENT = 11;
  public static final int TRUE = 16;
  public static final int LBRACKET = 22;
  public static final int LPAREN = 20;
  public static final int RBRACKET = 23;
  public static final int CONDITION = 12;
  public static final int EQUALS = 15;
  public static final int COMMA = 25;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int SET = 7;
  public static final int RUN = 8;
  public static final int RULE = 14;
  public static final int FALSE = 17;
  public static final int LOAD = 10;
  public static final int error = 1;
  public static final int BASIC = 6;
  public static final int ACT = 13;
  public static final int WHACKWHACK = 26;
}

